[package]
name = "instalator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
sevenz-rust = { version = "0.5.4", features = ["aes256"] }
steamlocate = "1.2.1"
